import { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, Alert, ScrollView, Modal, SafeAreaView, StatusBar, KeyboardAvoidingView, Platform, Image } from 'react-native';
import * as ImagePicker from 'react-native-image-picker';
import { activityAPI } from '../services/api';
import { storage } from '../utils/storage';

export default function CreateActivityScreen({ navigation }) {
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [activityDate, setActivityDate] = useState(new Date());
  const [showDatePicker, setShowDatePicker] = useState(false);
  const [dateMode, setDateMode] = useState('date');
  const [contractAmount, setContractAmount] = useState('');
  const [loading, setLoading] = useState(false);
  const [tempDate, setTempDate] = useState(new Date());
  const [imageBase64, setImageBase64] = useState(null);
  const [imageUrl, setImageUrl] = useState('');
  const [showImageModal, setShowImageModal] = useState(false);
  const [imageMode, setImageMode] = useState('upload');

  const formatDate = (date) => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');
    return `${year}-${month}-${day}T${hours}:${minutes}:00`;
  };

  const openDatePicker = (mode) => {
    setTempDate(activityDate);
    setDateMode(mode);
    setShowDatePicker(true);
  };

  const handleDateConfirm = () => {
    setActivityDate(tempDate);
    setShowDatePicker(false);
  };

  const adjustDate = (field, amount) => {
    const newDate = new Date(tempDate);
    if (field === 'year') newDate.setFullYear(newDate.getFullYear() + amount);
    if (field === 'month') newDate.setMonth(newDate.getMonth() + amount);
    if (field === 'day') newDate.setDate(newDate.getDate() + amount);
    if (field === 'hour') newDate.setHours(newDate.getHours() + amount);
    if (field === 'minute') newDate.setMinutes(newDate.getMinutes() + amount);
    setTempDate(newDate);
  };

  const handleSelectImage = () => {
    setShowImageModal(true);
  };

  const handleUploadImage = async () => {
    setShowImageModal(false);
    try {
      const result = await ImagePicker.launchImageLibrary({
        mediaType: 'photo',
        quality: 0.8,
        maxWidth: 800,
        maxHeight: 600,
        includeBase64: true,
      });

      if (result.assets && result.assets[0]) {
        setImageBase64(result.assets[0].base64);
        setImageUrl('');
        Alert.alert('成功', '图片已选择');
      }
    } catch (error) {
      console.error('Image picker error:', error);
      Alert.alert('错误', '选择图片失败');
    }
  };

  const handleTakePhoto = async () => {
    setShowImageModal(false);
    try {
      const result = await ImagePicker.launchCamera({
        mediaType: 'photo',
        quality: 0.8,
        maxWidth: 800,
        maxHeight: 600,
        includeBase64: true,
      });

      if (result.assets && result.assets[0]) {
        setImageBase64(result.assets[0].base64);
        setImageUrl('');
        Alert.alert('成功', '拍照成功');
      }
    } catch (error) {
      console.error('Camera error:', error);
      Alert.alert('错误', '拍照失败');
    }
  };

  const handleUseUrl = () => {
    setShowImageModal(false);
    Alert.prompt(
      '输入图片链接',
      '请输入图片的URL地址',
      [
        { text: '取消', style: 'cancel' },
        {
          text: '确定',
          onPress: (url) => {
            if (url && url.trim()) {
              setImageUrl(url.trim());
              setImageBase64(null);
              Alert.alert('成功', '图片链接已设置');
            }
          },
        },
      ],
      'plain-text',
      imageUrl
    );
  };

  const getAutoGeneratedImage = (name, description) => {
    const text = (name + ' ' + description).toLowerCase();

    const imageMap = {
      travel: [
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
        'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800',
      ],
      mountain: [
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
        'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
      ],
      sea: [
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
        'https://images.unsplash.com/photo-1519120944692-1a8d8cfc107f?w=800',
      ],
      beach: [
        'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800',
        'https://images.unsplash.com/photo-1520942702018-0862200e6873?w=800',
      ],
      city: [
        'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800',
        'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800',
      ],
      food: [
        'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
        'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
      ],
      coffee: [
        'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800',
        'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      ],
      sport: [
        'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800',
        'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
      ],
      run: [
        'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800',
        'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800',
      ],
      bike: [
        'https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800',
        'https://images.unsplash.com/photo-1533561052604-c3b9a9852d0e?w=800',
      ],
      swim: [
        'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=800',
        'https://images.unsplash.com/photo-1560090995-06c6f0c45e89?w=800',
      ],
      hiking: [
        'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
        'https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=800',
      ],
      camping: [
        'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800',
        'https://images.unsplash.com/photo-1478827536114-da961b7f86d2?w=800',
      ],
      park: [
        'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800',
        'https://images.unsplash.com/photo-1585928048467-30e8ad8e774c?w=800',
      ],
      music: [
        'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
        'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800',
      ],
      party: [
        'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
        'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800',
      ],
      movie: [
        'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800',
        'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800',
      ],
      game: [
        'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800',
        'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800',
      ],
      reading: [
        'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800',
        'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=800',
      ],
      photo: [
        'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
        'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800',
      ],
    };

    const defaultImages = [
      'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800',
      'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800',
      'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=800',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    ];

    for (const [keyword, urls] of Object.entries(imageMap)) {
      if (text.includes(keyword)) {
        const randomIndex = Math.floor(Math.random() * urls.length);
        return urls[randomIndex];
      }
    }

    const randomIndex = Math.floor(Math.random() * defaultImages.length);
    return defaultImages[randomIndex];
  };

  const handleAutoGenerate = () => {
    setShowImageModal(false);
    const generatedUrl = getAutoGeneratedImage(name, description);
    setImageUrl(generatedUrl);
    setImageBase64(null);
    Alert.alert('成功', '已根据活动内容自动生成图片');
  };

  const handleRemoveImage = () => {
    setImageBase64(null);
    setImageUrl('');
  };

  const handleCreate = async () => {
    if (!name || !contractAmount) {
      Alert.alert('提示', '请填写活动名称和契约金');
      return;
    }

    const user = await storage.getUser();
    if (!user) {
      Alert.alert('提示', '请先登录');
      navigation.navigate('Login');
      return;
    }

    let finalImageUrl = imageUrl;
    if (!finalImageUrl && !imageBase64) {
      finalImageUrl = getAutoGeneratedImage(name, description);
    }

    setLoading(true);
    try {
      const formData = new FormData();
      formData.append('userId', user.userId);
      formData.append('name', name);
      formData.append('description', description);
      formData.append('activityDate', formatDate(activityDate));
      formData.append('contractAmount', contractAmount);

      if (imageBase64) {
        formData.append('imageBase64', imageBase64);
      } else if (finalImageUrl) {
        formData.append('imageUrl', finalImageUrl);
      }

      await activityAPI.create(formData);
      Alert.alert('创建成功', '活动已发布', [
        { text: '确定', onPress: () => navigation.navigate('ActivityList') }
      ]);
    } catch (error) {
      Alert.alert('创建失败', error.response?.data?.message || '请稍后重试');
    } finally {
      setLoading(false);
    }
  };

  const renderDatePicker = () => (
    <Modal visible={showDatePicker} transparent animationType="fade" onRequestClose={() => setShowDatePicker(false)}>
      <View style={styles.modalOverlay}>
        <View style={styles.modalContent}>
          <Text style={styles.modalTitle}>{dateMode === 'date' ? '选择日期' : '选择时间'}</Text>

          <View style={styles.pickerContainer}>
            {dateMode === 'date' ? (
              <>
                <View style={styles.pickerRow}>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('year', -1)}>
                    <Text style={styles.pickerButtonText}>-</Text>
                  </TouchableOpacity>
                  <Text style={styles.pickerValue}>{tempDate.getFullYear()} 年</Text>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('year', 1)}>
                    <Text style={styles.pickerButtonText}>+</Text>
                  </TouchableOpacity>
                </View>
                <View style={styles.pickerRow}>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('month', -1)}>
                    <Text style={styles.pickerButtonText}>-</Text>
                  </TouchableOpacity>
                  <Text style={styles.pickerValue}>{tempDate.getMonth() + 1} 月</Text>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('month', 1)}>
                    <Text style={styles.pickerButtonText}>+</Text>
                  </TouchableOpacity>
                </View>
                <View style={styles.pickerRow}>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('day', -1)}>
                    <Text style={styles.pickerButtonText}>-</Text>
                  </TouchableOpacity>
                  <Text style={styles.pickerValue}>{tempDate.getDate()} 日</Text>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('day', 1)}>
                    <Text style={styles.pickerButtonText}>+</Text>
                  </TouchableOpacity>
                </View>
              </>
            ) : (
              <>
                <View style={styles.pickerRow}>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('hour', -1)}>
                    <Text style={styles.pickerButtonText}>-</Text>
                  </TouchableOpacity>
                  <Text style={styles.pickerValue}>{String(tempDate.getHours()).padStart(2, '0')} 时</Text>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('hour', 1)}>
                    <Text style={styles.pickerButtonText}>+</Text>
                  </TouchableOpacity>
                </View>
                <View style={styles.pickerRow}>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('minute', -1)}>
                    <Text style={styles.pickerButtonText}>-</Text>
                  </TouchableOpacity>
                  <Text style={styles.pickerValue}>{String(tempDate.getMinutes()).padStart(2, '0')} 分</Text>
                  <TouchableOpacity style={styles.pickerButton} onPress={() => adjustDate('minute', 1)}>
                    <Text style={styles.pickerButtonText}>+</Text>
                  </TouchableOpacity>
                </View>
              </>
            )}
          </View>

          <View style={styles.modalButtons}>
            <TouchableOpacity style={[styles.modalButton, styles.modalButtonCancel]} onPress={() => setShowDatePicker(false)}>
              <Text style={styles.modalButtonCancelText}>取消</Text>
            </TouchableOpacity>
            <TouchableOpacity style={[styles.modalButton, styles.modalButtonConfirm]} onPress={handleDateConfirm}>
              <Text style={styles.modalButtonConfirmText}>确认</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );

  const renderImageModal = () => (
    <Modal visible={showImageModal} transparent animationType="fade" onRequestClose={() => setShowImageModal(false)}>
      <View style={styles.modalOverlay}>
        <View style={styles.modalContent}>
          <Text style={styles.modalTitle}>选择图片</Text>

          <TouchableOpacity style={styles.imageOption} onPress={handleUploadImage}>
            <View style={styles.imageOptionIcon}>
              <Text style={styles.imageOptionEmoji}>🖼️</Text>
            </View>
            <View style={styles.imageOptionText}>
              <Text style={styles.imageOptionTitle}>上传图片</Text>
              <Text style={styles.imageOptionDesc}>从相册选择图片</Text>
            </View>
          </TouchableOpacity>

          <TouchableOpacity style={styles.imageOption} onPress={handleTakePhoto}>
            <View style={styles.imageOptionIcon}>
              <Text style={styles.imageOptionEmoji}>📷</Text>
            </View>
            <View style={styles.imageOptionText}>
              <Text style={styles.imageOptionTitle}>拍照</Text>
              <Text style={styles.imageOptionDesc}>使用相机拍摄</Text>
            </View>
          </TouchableOpacity>

          <TouchableOpacity style={styles.imageOption} onPress={handleAutoGenerate}>
            <View style={styles.imageOptionIcon}>
              <Text style={styles.imageOptionEmoji}>✨</Text>
            </View>
            <View style={styles.imageOptionText}>
              <Text style={styles.imageOptionTitle}>自动生成</Text>
              <Text style={styles.imageOptionDesc}>根据活动描述智能生成</Text>
            </View>
          </TouchableOpacity>

          <TouchableOpacity style={styles.imageOption} onPress={handleUseUrl}>
            <View style={styles.imageOptionIcon}>
              <Text style={styles.imageOptionEmoji}>🔗</Text>
            </View>
            <View style={styles.imageOptionText}>
              <Text style={styles.imageOptionTitle}>图片链接</Text>
              <Text style={styles.imageOptionDesc}>复制图片URL地址</Text>
            </View>
          </TouchableOpacity>

          <TouchableOpacity style={styles.modalCancelButton} onPress={() => setShowImageModal(false)}>
            <Text style={styles.modalCancelText}>取消</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );

  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="dark-content" backgroundColor="#F8FAFC" />
      <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={styles.keyboardView}>
        <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
          <View style={styles.container}>
            <View style={styles.header}>
              <TouchableOpacity style={styles.backButton} onPress={() => navigation.goBack()}>
                <Text style={styles.backButtonText}>←</Text>
              </TouchableOpacity>
              <Text style={styles.headerTitle}>发布活动</Text>
              <View style={{ width: 40 }} />
            </View>

            <View style={styles.formCard}>
              <View style={styles.inputGroup}>
                <Text style={styles.inputLabel}>活动名称</Text>
                <TextInput
                  style={styles.input}
                  placeholder="请输入活动名称"
                  placeholderTextColor="#BDBDBD"
                  value={name}
                  onChangeText={setName}
                />
              </View>

              <View style={styles.inputGroup}>
                <Text style={styles.inputLabel}>活动描述</Text>
                <TextInput
                  style={[styles.input, styles.textArea]}
                  placeholder="请输入活动描述..."
                  placeholderTextColor="#BDBDBD"
                  value={description}
                  onChangeText={setDescription}
                  multiline
                  numberOfLines={4}
                  textAlignVertical="top"
                />
              </View>

              <View style={styles.inputGroup}>
                <Text style={styles.inputLabel}>活动图片</Text>
                <TouchableOpacity style={styles.imageSelector} onPress={handleSelectImage}>
                  {imageBase64 ? (
                    <Image source={{ uri: `data:image/jpeg;base64,${imageBase64}` }} style={styles.previewImage} />
                  ) : imageUrl ? (
                    <Image source={{ uri: imageUrl }} style={styles.previewImage} resizeMode="cover" />
                  ) : (
                    <View style={styles.imagePlaceholder}>
                      <Text style={styles.imagePlaceholderIcon}>🖼️</Text>
                      <Text style={styles.imagePlaceholderText}>点击添加图片</Text>
                    </View>
                  )}
                </TouchableOpacity>
                {(imageBase64 || imageUrl) && (
                  <TouchableOpacity style={styles.removeImageBtn} onPress={handleRemoveImage}>
                    <Text style={styles.removeImageBtnText}>移除图片</Text>
                  </TouchableOpacity>
                )}
              </View>

              <View style={styles.inputGroup}>
                <Text style={styles.inputLabel}>活动时间</Text>
                <View style={styles.dateRow}>
                  <TouchableOpacity style={styles.datePicker} onPress={() => openDatePicker('date')}>
                    <View style={styles.dateIcon}>
                      <Text style={styles.dateIconText}>📅</Text>
                    </View>
                    <View style={styles.dateContent}>
                      <Text style={styles.dateLabel}>日期</Text>
                      <Text style={styles.dateValue}>
                        {activityDate.getFullYear()}-{String(activityDate.getMonth() + 1).padStart(2, '0')}-{String(activityDate.getDate()).padStart(2, '0')}
                      </Text>
                    </View>
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.datePicker} onPress={() => openDatePicker('time')}>
                    <View style={styles.dateIcon}>
                      <Text style={styles.dateIconText}>🕐</Text>
                    </View>
                    <View style={styles.dateContent}>
                      <Text style={styles.dateLabel}>时间</Text>
                      <Text style={styles.dateValue}>
                        {String(activityDate.getHours()).padStart(2, '0')}:{String(activityDate.getMinutes()).padStart(2, '0')}
                      </Text>
                    </View>
                  </TouchableOpacity>
                </View>
              </View>

              <View style={styles.inputGroup}>
                <Text style={styles.inputLabel}>契约金</Text>
                <View style={styles.amountInput}>
                  <Text style={styles.amountIcon}>💰</Text>
                  <TextInput
                    style={styles.amountField}
                    placeholder="0.00"
                    placeholderTextColor="#BDBDBD"
                    value={contractAmount}
                    onChangeText={setContractAmount}
                    keyboardType="decimal-pad"
                  />
                  <Text style={styles.amountUnit}>元</Text>
                </View>
                <Text style={styles.amountHint}>报名者需支付的契约金，活动完成后返还</Text>
              </View>

              <TouchableOpacity
                style={[styles.submitButton, loading && styles.submitButtonDisabled]}
                onPress={handleCreate}
                disabled={loading}
                activeOpacity={0.8}
              >
                <Text style={styles.submitButtonText}>{loading ? '发布中...' : '立即发布'}</Text>
              </TouchableOpacity>
            </View>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
      {renderDatePicker()}
      {renderImageModal()}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  backButtonText: {
    fontSize: 20,
    color: '#1E1B4B',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E1B4B',
  },
  formCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 6,
    marginTop: 8,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
    opacity: 0.8,
  },
  input: {
    height: 52,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 15,
    color: '#1F2937',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  textArea: {
    height: 100,
    paddingTop: 14,
    lineHeight: 22,
  },
  imageSelector: {
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderStyle: 'dashed',
  },
  previewImage: {
    width: '100%',
    height: 180,
  },
  imagePlaceholder: {
    height: 120,
    backgroundColor: '#F9FAFB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imagePlaceholderIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  imagePlaceholderText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  removeImageBtn: {
    marginTop: 8,
    alignSelf: 'flex-start',
  },
  removeImageBtnText: {
    fontSize: 13,
    color: '#EF4444',
  },
  dateRow: {
    flexDirection: 'row',
    gap: 12,
  },
  datePicker: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  dateIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#EEF2FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  dateIconText: {
    fontSize: 18,
  },
  dateContent: {
    flex: 1,
  },
  dateLabel: {
    fontSize: 11,
    color: '#9CA3AF',
    marginBottom: 2,
  },
  dateValue: {
    fontSize: 15,
    color: '#1F2937',
    fontWeight: '500',
  },
  amountInput: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  amountIcon: {
    fontSize: 20,
    marginRight: 10,
  },
  amountField: {
    flex: 1,
    height: 52,
    fontSize: 18,
    color: '#1F2937',
    fontWeight: '600',
  },
  amountUnit: {
    fontSize: 15,
    color: '#6B7280',
  },
  amountHint: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 8,
  },
  submitButton: {
    height: 54,
    backgroundColor: '#6366F1',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  submitButtonDisabled: {
    backgroundColor: '#A5B4FC',
    shadowOpacity: 0,
    elevation: 0,
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '85%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E1B4B',
    textAlign: 'center',
    marginBottom: 20,
  },
  imageOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  imageOptionIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#EEF2FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  imageOptionEmoji: {
    fontSize: 20,
  },
  imageOptionText: {
    flex: 1,
  },
  imageOptionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1E1B4B',
    marginBottom: 2,
  },
  imageOptionDesc: {
    fontSize: 12,
    color: '#6B7280',
  },
  modalCancelButton: {
    marginTop: 16,
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalCancelText: {
    fontSize: 15,
    color: '#6B7280',
    fontWeight: '600',
  },
  pickerContainer: {
    marginBottom: 24,
  },
  pickerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  pickerButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EEF2FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerButtonText: {
    fontSize: 20,
    color: '#6366F1',
    fontWeight: 'bold',
  },
  pickerValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1E1B4B',
    width: 120,
    textAlign: 'center',
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalButtonCancel: {
    backgroundColor: '#F3F4F6',
  },
  modalButtonCancelText: {
    fontSize: 15,
    color: '#6B7280',
    fontWeight: '600',
  },
  modalButtonConfirm: {
    backgroundColor: '#6366F1',
  },
  modalButtonConfirmText: {
    fontSize: 15,
    color: '#fff',
    fontWeight: '600',
  },
});